### ISSUE TITLE
display issue on window

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [jiborobot/floss#6]
Hi ! 
Thank for this awesome repository ! =)

I have a display issue on window.

The reporter out this :

```
←[0m←[0m
←[0m  _forEachDeep :: tag:String => Object => Function => undefined←[0m
  ←[32m  ÔêÜ←[0m←[90m should call func in all children←[0m

←[0m  _mapDeep :: tag:String => Object => Function => Object←[0m
  ←[32m  ÔêÜ←[0m←[90m should call func in all children←[0m
  ←[32m  ÔêÜ←[0m←[90m should return an object with the same structure←[0m
  ←[32m  ÔêÜ←[0m←[90m should return an object with children name equal ok←[0m

←[0m  .createFrom :: Object => Container←[0m
  ←[32m  ÔêÜ←[0m←[90m should expose createFrom←[0m
  ←[31m  1) should return a Container←[0m


←[92m ←[0m←[32m 5 passing←[0m←[90m (59ms)←[0m
←[31m  1 failing←[0m

←[0m  1) .createFrom :: Object => Container should return a Container:
←[0m←[31m     TypeError: Cannot read property 'should' of undefined←[0m←[90m
      at Context.it (C:\Users\florian\Main\modules\pixi-createfrom\test\index.js:90:14)
      at callFn (C:\Users\florian\Main\modules\pixi-createfrom\node_modules\floss\node_modules\mocha\lib\runnable.js:326:21)
```

Do you know where this issue come from ?

**Comment by bigtimebuddy** [comment]
Mocha logs out message using ANSI colors for colorizing the output. On Windows, this is not supported. I would suggest you look at: https://github.com/adoxa/ansicon to enable ANSI on Windows.
